#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width        	${border}
bspc config border_radius		      0
bspc config window_gap          	20
bspc config pointer_modifier		  super
bspc config pointer_action1		    move
bspc config pointer_action3		    resize_side
bspc config split_ratio         	0.5
bspc config top_padding 		      0
bspc config bottom_padding		    40
bspc config left_padding		      0
bspc config right_padding		      0
bspc config normal_border_color 	'#EEEEEE'
bspc config active_border_color 	'#DDFFFF'
bspc config focused_border_color 	'#DDFFFF'
bspc config borderless_monocle   	false
bspc config gapless_monocle      	false
bspc config focus_follows_pointer	true
